# Rapimax — Cloudflare Worker + Assets
name = "rapimax-site"
compatibility_date = "2024-12-01"
main = "functions/worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rapimax-prod"
database_id = "80d06894-83c2-4d45-afe7-1f1b1889cf7b"
